version: '3.3'

services:
    db:
        build:
            context: mysql
        env_file: ./.env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - "./.data/db:/var/lib/mysql"
            - "./.data/mysql/backup:/var/db/backup"
        ports:
            - ${MYSQL_PORT}:3306
    web:
        depends_on:
            - db
        env_file: ./.env
        build:
            context: php-apache
            args:
                TIMEZONE: ${TIMEZONE}
                ENVIRONMENT: ${ENVIRONMENT}
        ports:
            - ${PUBLIC_IPV4}:${APACHE_PORT}:80
            - ${PUBLIC_IPV4}:${APACHE_PORT_SSL}:443
        links:
            - db
            - smtp
        volumes:
            - ${PROJECT_DIRECTORY}:/var/www/www
            - ../cert:/var/www/cert
            - ../logs:/var/www/logs
#            - ${SSH_KEYS_PATH}:/var/www/.ssh
#            - ./php7.2-apache/sites-available/${ENVIRONMENT}/:/etc/apache2/sites-enabled/
    smtp:
        image: namshi/smtp
        restart: always
        env_file: ./.env
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
          - PMA_ARBITRARY=1
        restart: always
        ports:
          - ${PHPMYADMIN_PORT}:80
        volumes:
          - ./.data/phpmyadmin/sessions:/sessions